### ISSUE TITLE
Search by Item Name

### ISSUE THREAD

**Issue by philihp** [philihp/goonql#19]
I'm often doing queries like this

```graphql
query {
  type(typeID: "3514") {
    typeID
    typeName
    builtBy {
      manufacture(blueprint: 0, rig: 0.02, runs: 1) {
        products {
          quantity
        }
        materials {
          quantity
          type {
            typeID
            typeName
          }
        }
      }
    }
  }
}
```

https://goonql.philihp.com/api/graphql?query=query+GSF+%7B%0A++type%28typeID%3A+%223514%22%29+%7B%0A++++typeID%0A++++typeName%0A++++builtBy+%7B%0A++++++manufacture%28blueprint%3A+0%2C+rig%3A+0.02%2C+runs%3A+1%29+%7B%0A++++++++products+%7B%0A++++++++++quantity%0A++++++++%7D%0A++++++++materials+%7B%0A++++++++++quantity%0A++++++++++type+%7B%0A++++++++++++typeID%0A++++++++++++typeName%0A++++++++++%7D%0A++++++++%7D%0A++++++%7D%0A++++%7D%0A++%7D%0A%7D

But often I'm just issuing these by hand, and really just want to search for an item name, and I often have the exact name so I want to do something like

```graphql
query {
  type(typeID: "Revenant") {
    ...
  }
}
```

**Comment by probro27** [comment]
I would like to take this one if possible! Please assign to me :)

**Comment by philihp** [comment]
@probro27 just make a PR. i'll get you hacktoberfest credit for your work, even if it turns out to be redundant.

**Comment by probro27** [comment]
Cool. thanks @philihp . 
I'll work on this.

**Comment by probro27** [comment]
Hey @philihp shouldn't the query be something like 
```graphql
query {
  type(typeName: "Revenant") {
    ...
  }
}
``` 
or do you want me to check if the typeId is integer or string and query based on that?
